<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;


function vote_page_attachments_alter(&$page) {
        
    $path = $current_path = \Drupal::service('path.current')->getPath();
    $routeName = \Drupal::routeMatch()->getRouteName();

    if (explode(".", $routeName)[0] === 'vote') {
        $page['#attached']['library'][] = 'vote/vote_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/common_assets';    // for "Rating"
        $page['#attached']['library'][] = 'common/common_modal';    // for "Access Control", put this line after "common/content_table"
    }
    
}


function vote_theme($existing, $type, $theme, $path) {

    return [
        'vote-home' =>[
            'variables' => [
                'items' => NULL,
                'my_user_id' => NULL,
                'tagsUrl' => NULL,
                'pager' => NULL,
            ],
        ],
            
    ];

}


/**
 * Implements hook_help().
 */
function vote_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.vote':
        return '<p>' . t('Vote module that provides KICP vote.') . '</p>';
        break;
    }
  }  

