<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;
use Drupal\activities\Common\ActivitiesDatatable;


function activities_page_attachments_alter(&$page) {
        
    $path = $current_path = \Drupal::service('path.current')->getPath();
    if ( str_contains($path, '/activities')) {
        $page['#attached']['library'][] = 'activities/activities_key';
        $page['#attached']['library'][] = 'common/common_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/common_assets';   
        

        if ( str_contains($path, 'activities_item_add') || str_contains($path, 'activities_item_change')  || str_contains($path, 'activities_detail') || str_contains($path, 'activities_tag') || str_contains($path, 'activities_deliverable_add') || str_contains($path, 'activities_deliverable_change') ) {
            $page['#attached']['library'][] = 'common/content_tags';
        }
        
        
        if ( str_contains($path, '/activities_detail')) 
        {
            $page['#attached']['library'][] = 'activities/activities_gallery';
        }

     }
}


function activities_theme($existing, $type, $theme, $path) {

    return [
        'activities-main' =>[
            'variables' => [
                'items' => NULL,
                'groups' => NULL,
                'types' => NULL,
                'events' => NULL,
                'copitems' => NULL,
                'my_user_id' => NULL,
                'following' => NULL,
            ],
        ],
        'activities-admin-photos' =>[
            'variables' => [
                'items' => NULL,
                'type_id' => NULL,
                'evt_id' => NULL,
                'pager' => NULL,
            ],
        ],
        'activities-admin-deliverable' =>[
            'variables' => [
                'items' => NULL,
                'type_id' => NULL,
                'evt_id' => NULL,
                'pager' => NULL,
            ],
        ],        
        'activities-details' =>[
            'variables' => [
                'items' => NULL,
                'groups' => NULL,
                'types' => NULL,
            ],
        ],        
        'activities-admin'=>[
            'variables' => [
                'items' => NULL,
                'groups' => NULL,
                'types' => NULL,
                'events' => NULL,
                'copitems' => NULL,
            ],
        ],
        'activities-admin-category'=>[
            'variables' => [
                'items' => NULL,
                'pager' => NULL,
            ],
        ],
        'activities-admin-cop'=>[
            'variables' => [
                'items' => NULL,
                'group' => NULL,
                'pager' => NULL,
            ],
        ],
        'activities-admin-events' =>[
            'variables' => [
                'items' => NULL,
                'pager' => NULL,
            ],
        ],        
        'activities-photo' =>[
            'variables' => [
                'items' => NULL,
                'groups' => NULL,
                'types' => NULL,
                'evt_id' => NULL,
                'PhotoPerPage' => NULL,
            ],
        ],
        'activities-deliverable' =>[
            'variables' => [
                'items' => NULL,
                'evt_id' => NULL,
            ],
        ],        
        'activities-enrollment-status' =>[
            'variables' => [
                'items' => NULL,
                'event' => NULL,
            ],
        ],
        'activities-enrollment-list' =>[
            'variables' => [
                'items' => NULL,
                'event' => NULL,
            ],
        ],        
        'activities-tags' =>[
            'variables' => [
                'act_items' => NULL,
                'tags' => NULL,
                'tagsUrl' => NULL,                
                'pager' => NULL,
            ],
        ],        
    ];

}

function activities_preprocess_page_title(&$variables) {
    $route_match = \Drupal::routeMatch();
    $route_name = $route_match->getRouteName();
    if ($route_name === "activities.activities_detail") {
        $evt_id = $route_match->getParameter('evt_id');
        $evt  = ActivitiesDatatable::getEventInfo($evt_id);
        if ( $evt ) {
            $evt_name = $evt->evt_name;
            $variables['title'] = $evt_name;
        }
    }
  }

 function activities_preprocess_html(&$variables) {
    $route_match = \Drupal::routeMatch();
    $route_name = $route_match->getRouteName();
    if ($route_name === "activities.activities_detail") {
        $evt_id = $route_match->getParameter('evt_id');
        $evt  = ActivitiesDatatable::getEventInfo($evt_id);
        if ( $evt ) {
            $evt_name = $evt->evt_name;
            $variables['head_title']['title'] = $evt_name;
        }
    }
  }  


/**
 * Implements hook_help().
 */
function activities_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.activities':
        return '<p>' . t('Activities module that provides KICP Activities.') . '</p>';
        break;
    }
  }  
    