testform.settings:
  type: config_object
  label: Test From Content Type Settigns
  mapping:
    allowed_types:
     type: sequence
     label: Content types the Test From can display on
     sequence:
       type: string
       label: Content type
