<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;

function survey_page_attachments_alter(&$page) {
    
    $path = $current_path = \Drupal::service('path.current')->getPath();

    if (str_contains($path, '/survey')) {
        $page['#attached']['library'][] = 'survey/survey_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/common_assets';    // for "Rating"
        $page['#attached']['library'][] = 'common/common_modal';    // for "Access Control", put this line after "common/content_table"

    }
    
}


function survey_theme($existing, $type, $theme, $path) {

    return [
        'survey-home' =>[
            'variables' => [
                'items' => NULL,
                'pager' => NULL,
            ],
        ],
            
    ];

}



/**
 * Implements hook_help().
 */
function survey_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.survey':
        return '<p>' . t('Survey module that provides KICP survey.') . '</p>';
        break;
    }
  }  