<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;

function survey_page_attachments_alter(&$page) {
    
    $path = $current_path = \Drupal::service('path.current')->getPath();
    $routeName = \Drupal::routeMatch()->getRouteName();

    if (explode(".", $routeName)[0] === 'survey') {
        $page['#attached']['library'][] = 'survey/survey_key';
        $page['#attached']['library'][] = 'common/content_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/common_assets';    // for "Rating"
        $page['#attached']['library'][] = 'common/common_modal';    // for "Access Control", put this line after "common/content_table"
        $page['#attached']['library'][] = 'profile/profile_key';    // for "Access Control", put this line after "common/content_table"

        if ($routeName== 'survey.survey_view') {
            $page['#attached']['library'][] = 'survey/survey_form';
        }
        if ($routeName== 'survey.survey_content') {
            $page['#attached']['library'][] = 'common/content_tags';
        }

    }
    
}


function survey_theme($existing, $type, $theme, $path) {

    return [
        'survey-home' =>[
            'variables' => [
                'items' => NULL,
                'tagsUrl' => NULL,
                'pager' => NULL,
            ],
        ],
            
    ];

}



/**
 * Implements hook_help().
 */
function survey_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.survey':
        return '<p>' . t('Survey module that provides KICP survey.') . '</p>';
        break;
    }
  }  