<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;

function forum_page_attachments_alter(&$page) {
    
    $path = $current_path = \Drupal::service('path.current')->getPath();

    if (str_contains($path, '/forum')) {
        $page['#attached']['library'][] = 'forum/forum_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/common_assets';    // for "Rating"
        $page['#attached']['library'][] = 'common/common_modal';    // for "Access Control", put this line after "common/content_table"

        if (str_contains($path, '/forum_topic_add')  ) {
            $page['#attached']['library'][] = 'common/content_tags';
        }

        if (str_contains($path, '/forum_tag') || str_contains($path,'/forum_view_topic')  ) {
            $page['#attached']['library'][] = 'common/content_table';
        }


    }
    
}


function forum_theme($existing, $type, $theme, $path) {

    return [
        'forum-home' =>[
            'variables' => [
                'latest' => NULL,
                'forums' => NULL,
                'my_user_id'=> NULL,
            ],
        ],
        'forum-forum' =>[
            'variables' => [
                'posts' => NULL,
                'forum_info' => NULL,
                'my_user_id'=> NULL,
                'pager' => NULL,
            ],
        ],
        'forum-tags' =>[
            'variables' => [
                'posts' => NULL,
                'tags' => NULL,
                'tagsUrl' => NULL,
                'my_user_id'=> NULL,
                'pager' => NULL,
            ],
        ],        
        'forum-post' =>[
            'variables' => [
                'threads' => NULL,
                'forum_info' => NULL,
                'tags' => NULL,
                'my_user_id'=> NULL,
                'pager' => NULL,
            ],
        ],

            
    ];

}



/**
 * Implements hook_help().
 */
function forum_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.forum':
        return '<p>' . t('Forum module that provides KICP forum.') . '</p>';
        break;
    }
  }  