<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;

function bookmark_page_attachments_alter(&$page) {

    
    $path = $current_path = \Drupal::service('path.current')->getPath();
    

    if ( str_contains($path, '/bookmark') ) {

        $page['#attached']['library'][] = 'bookmark/bookmark_key';
        $page['#attached']['library'][] = 'common/common_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/content_tags';
    }

}


function bookmark_theme($existing, $type, $theme, $path) {

    return [
        'bookmark-list' =>[
            'variables' => [
                'items' => NULL,
                'pager' => NULL,
                'tagsUrl' => NULL,
            ],
        ],   

    ];

}



function bookmark_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.bookmark':
        return '<p>' . t('Bookmark module that provides KICP blogs.') . '</p>';
        break;
    }
  }  

