<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;
use Drupal\video\Common\VideoDatatable;


function video_page_attachments_alter(&$page) {
        
    $path = \Drupal::service('path.current')->getPath();
    $routeName = \Drupal::routeMatch()->getRouteName();

    if ( str_contains($path, '/video')  ) {

        $page['#attached']['library'][] = 'video/video_key';

        if($routeName === 'video.video_entrylist') {
            $page['#attached']['library'][] = 'common/jssor_slider';
        }

        if($routeName === 'video.video_list' || $routeName === 'video.video_tag' ) 
           $page['#attached']['library'][] = 'common/common_assets';    // for "Rating"

        if($routeName === 'video.video_list' || $routeName === 'video.video_tag' || $routeName === 'video.admin_content' || $routeName === 'video.admin_video_content' || $routeName === 'video.video_event_privilege') {
            $page['#attached']['library'][] = 'common/content_table';
        }

        if($routeName === 'video.add_event_data' || $routeName === 'video.change_event_data') {
            $page['#attached']['library'][] = 'common/content_tags';
        }
        if($routeName === 'video.video_playback') {
            $page['#attached']['library'][] = 'video/video_js';
        }


    }
    

}


function video_theme($existing, $type, $theme, $path) {

    return [
        'video-home' =>[
            'variables' => [
                'items' => NULL,
                'items_right' => NULL,
            ],
        ],
        'video-list' =>[
            'variables' => [
                'media_event_id'=> NULL,
                'items' => NULL,
                'rating' => NULL,
                'tags' => NULL,
                'event_info' => NULL,
                'my_user_id' => NULL,
                'following' => NULL,                
                'pager' => NULL,
            ],
        ],
        'video-tags' =>[
            'variables' => [
                'items' => NULL,
                'tags' => NULL,
                'tagsUrl' => NULL,
                'pager' => NULL,
            ],
        ],
        'video-admin' =>[
            'variables' => [
                'items' => NULL,
                'pager' => NULL,
            ],
        ],
        'video-admin-video' =>[
            'variables' => [
                'items' => NULL,
                'media_event_id'  => NULL,
                'eventname' => NULL,
                'pager' => NULL,
            ],
        ],
        'video-admin-privilege' =>[
            'variables' => [
                'items' => NULL,
                'eventname' => NULL,
                'privilege_group' => NULL,
                'pager' => NULL,
            ],
        ],
        'video-event.selection' =>[
            'variables' => [
                'items' => NULL,
            ],
        ],
        'video-playback' =>[
            'variables' => [
                'media' => NULL,
                'event_info' => NULL,
            ],
        ],
        
    ];

}


function video_preprocess_page_title(&$variables) {
    $route_match = \Drupal::routeMatch();
    $route_name = $route_match->getRouteName();
    if ($route_name === "video.video_playback") {
        $media_id = $route_match->getParameter('media_id');
        $media = VideoDatatable::getVideoInfo($media_id);
        if ($media) {
            $title = preg_replace( "/<br>|\n|<br( ?)\/>/", " ", $media['media_title']);        
            $variables['title'] = $title;
        }
    }
  }

/**
 * Implements hook_help().
 */
function video_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.video':
        return '<p>' . t('Video module that provides KICP blogs.') . '</p>';
        break;
    }
  }  
    