<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;


function video_page_attachments_alter(&$page) {
        
        $page['#attached']['library'][] = 'video/video_key';
        $path = $current_path = \Drupal::service('path.current')->getPath();
        if ( $path == '/video')  {
            $page['#attached']['library'][] = 'video/video_home';
        }        


}

/*
function video_theme($existing, $type, $theme, $path) {

    return [
        'blogs-home' =>[
            'variables' => [
                'items' => NULL,
            ],
        ],

    ];

}
*/


/*
function fileshare_file_download($uri) {

    $scheme = \Drupal\Core\StreamWrapper\StreamWrapperManager::getScheme($uri);
    if ($scheme === 'private') {
        $uri_target = array();
        $uri_target = explode('/', \Drupal\Core\StreamWrapper\StreamWrapperManager::getTarget($uri));

        return $uri;
    } else {
        return $uri;
    }
}
*/

/**
 * Implements hook_help().
 */
function video_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.video':
        return '<p>' . t('Video module that provides KICP blogs.') . '</p>';
        break;
    }
  }  
    