<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity;
use Drupal\file\Entity\File;

function mainpage_page_attachments_alter(&$page) {
    
    $path = $current_path = \Drupal::service('path.current')->getPath();
    $routeName = \Drupal::routeMatch()->getRouteName();

    if (explode(".", $routeName)[0] === 'mainpage') {
        $page['#attached']['library'][] = 'common/common_assets';    // for "Rating"
        $page['#attached']['library'][] = 'mainpage/mainpage_key';
        $page['#attached']['library'][] = 'common/content_table';
        $page['#attached']['library'][] = 'common/content_tags';
        $page['#attached']['library'][] = 'common/common_modal';
        
    }
    
}


function mainpage_theme($existing, $type, $theme, $path) {

    return [
        'mainpage-home' =>[
            'variables' => [
                'editor_choice' => NULL,
                'items' => NULL,
                'cop_tags' => NULL,
                'other_tags' => NULL,
                'my_user_id' => NULL,
                'followers' => NULL,
                'myRecordOnly' => NULL,
                'myfollowed' => NULL,
                'myFollowing' => NULL,
            ],
        ],
        'mainpage-tags' =>[
            'variables' => [
                'items' => NULL,
                'tags' => NULL,
                'tagsUrl' => NULL,
                'pager' => NULL,                
            ],
        ],
        'mainpage-follow-table'=>[
            'variables' => [
                'items' => NULL,
                'choices' => NULL,
                'my_user_id' => NULL,
            ],
        ],
    ];

}



/**
 * Implements hook_help().
 */
function mainpage_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.mainpage':
        return '<p>' . t('Mainpage module that provides KICP home page.') . '</p>';
        break;
    }
  }  